### ISSUE TITLE
Error getting private playlist

### ISSUE THREAD

**Issue by Gabriel-Severo** [LevitatingBusinessMan/yt-playlist-scraper#1]
Hello, I'm trying to get a private playlist using the code
```js
const playlists = require("yt-playlist-scraper")
playlists("FLctePPsTK5i0t4zpVwKIXpg")
.then(playListData => {
	console.log(playListData)
})
.catch(err => {
	console.log(err)
})
```
But I get the following error that cannot be handled using error handling
```
/home/user/teste/node_modules/yt-playlist-scraper/src/index.js:54
                                .microformatDataRenderer
                                 ^

TypeError: Cannot read property 'microformatDataRenderer' of undefined
    at IncomingMessage.<anonymous> (/home/user/teste/node_modules/yt-playlist-scraper/src/index.js:54:6)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Another problem is that if the if [line 49](https://github.com/LevitatingBusinessMan/yt-playlist-scraper/blob/master/src/index.js#L49) is true, the promise will never be resolved and will be running forever
```js
if (!ytInitialData)
	return
```
One way I've found to solve the problem so far is this, but I don't know if it would be right
```js
if (!ytInitialData || !ytInitialData.microformat) {
	reject(Error("No playlist found"))
	return
}
```

**Comment by LevitatingBusinessMan** [comment]
Hey, thanks for opening an issue about this.
I hope you understand that this script will never be able to fetch private playlists.
Aside from that the error handling should now have 2 failsafes to prevent issues like this.

**Comment by LevitatingBusinessMan** [comment]
I'll add, the reason that it can't fetch a private playlist is because the script will always access youtube anonymously. If you perse want to grab a private playlist you'll have to alter the code to allow requests as a logged in user.
